import type { Project } from "@/types/project.type";

export function useProjects() {
  const data: Project[] = [
    {
      title: "Onsite 2 | Full Rebuild of Core Logistics App",
      description: "Co-led the end-to-end architectural migration of the company’s flagship logistics platform from a legacy jQuery monolith to a modern full-stack ecosystem. By implementing Next.js and .NET Core, I achieved a 4.5x improvement in First Contentful Paint (0.4s) and a 96 Performance score in Lighthouse. This modernization significantly enhanced user experience while eliminating approximately $20,000 USD in projected outsourcing costs",
      image: "/img/projects/onsite2/main.webp",
      tags: ["C#", ".NET", "TypeScript", "React", "Next.js", "Tailwind CSS"],
      featured: false,
      level: "Professional",
      caseStudyLink: "/cases/onsite2",
      liveLink: "https://app.pktuno.mx/",
    },
    {
      title: "Management | Enhancements and Maintenance",
      description: "Designed and scaled core backend modules for the company’s internal logistics engine. Developed server-side logic in C#/.NET to process raw operational telemetry into automated analytics and reporting tools, significantly reducing manual monitoring and streamlining administrative workflows for internal stakeholders.",
      image: "/img/projects/management/main.webp",
      tags: ["C#", ".NET", "JavaScript", "React", "Tailwind CSS"],
      liveLink: "https://mgmtview.pktuno.mx/",
      featured: false,
      level: "Professional",
      caseStudyLink: "/cases/management",
    },
    {
      title: "Cloud Storage Migration | Performance Optimization",
      description: "Engineered a high-efficiency storage migration, offloading legacy file records from MySQL (Base64) to AWS S3. By eliminating the 33% storage overhead inherent in Base64 encoding, I reduced database bloat and improved query latency, resulting in a 30% reduction in storage costs and more reliable data backups for the enterprise",
      image: "/img/projects/s3/s3-migration.png",
      tags: ["C#", ".NET", "SQL", "AWS S3"],
      featured: false,
      level: "Professional",
      caseStudyLink: "/cases/s3-migration",
    },
    {
      title: "AI Carrier Integration | Semantic Error Layer",
      description: "Developed an AI-driven normalization pipeline to standardize disparate error responses from multiple global carriers into a single canonical format. Implemented a Semantic Cache layer to optimize LLM token usage and minimize API latency, providing a unified error interface that streamlines troubleshooting.",
      image: "/img/projects/error-translation/error-translation.png",
      tags: ["C#", ".NET", "SQL", "AWS S3"],
      featured: false,
      level: "Professional",
      caseStudyLink: "/cases/error-translation",
    },
    {
      title: "Regina & Gael Studio | Fullstack E-commerce Platform",
      description: "Architected a secure digital-asset delivery system using AWS S3 and Signed URLs, ensuring content protection and automated distribution following PayPal verification. Developed a custom end-to-end architecture to handle high-resolution digital downloads, reducing manual overhead for the business owner.",
      image: "/img/projects/regina/main.webp",
      tags: [
        "TypeScript",
        "React",
        "Next.js",
        "Tailwind CSS",
        "MongoDB",
        "AWS",
      ],
      githubLink: "https://github.com/JuanP-VT/regis",
      caseStudyLink: "/cases/regina",
      featured: false,
      level: "Freelance",
    },
    {
      title: "Okayhey Temazcal | Web Presence + CMS Integration",
      description: "Implemented a Headless CMS (Contentful) to decouple content management from the frontend, enabling non-technical stakeholders to perform independent site updates without code deployments. Optimized site performance and SEO through Next.js server-side rendering, significantly increasing client engagement and discovery.",
      image: "/img/projects/okahey/main.webp",
      tags: ["TypeScript", "React", "Next.js", "Tailwind CSS"],
      githubLink: "https://github.com/JuanP-VT/okahey",
      featured: false,
      level: "Freelance",
    },
    {
      title: "PC Hub | Fullstack Ecommerce Learning Project",
      description: "Developed a fully functional eCommerce prototype from scratch to showcase fullstack skills. Features include user authentication, product catalog with filters, shopping cart, checkout, user profiles, and an admin panel for product management.",
      image: "/img/projects/learning/pc-hub.webp",
      tags: ["TypeScript", "React", "Next.js", "Tailwind CSS", "MongoDB"],
      liveLink: "https://store-juanp-vt.vercel.app",
      githubLink: "https://github.com/JuanP-VT/pc-ecommerce",
      featured: true,
      level: "Learning",
      caseStudyLink: "/cases/pc-hub",
    },
    {
      title: "Inventory Manager App | Fullstack CRUD System",
      description: "Developed a fullstack inventory management tool. Implemented a robust Fullstack architecture featuring NoSQL schema design, and a responsive administrative dashboard.",
      image: "/img/projects/learning/inventory.webp",
      tags: ["JavaScript", "React", "Express.js", "MongoDB"],
      liveLink: "https://juanp-vt.github.io/store-inventory/",
      githubLink: "https://github.com/JuanP-VT/store-inventory",
      featured: false,
      level: "Learning",
    },
    {
      title: "Curriculum Builder | Dynamic PDF Generator",
      description: "Created a React application that allows users to input personal and professional information and generate a downloadable PDF résumé. Built with TypeScript using class-based components, this project deepened my understanding of component state, lifecycle methods, and handling structured user input.",
      image: "/img/projects/learning/cv.webp",
      tags: ["TypeScript", "React", "CSS"],
      liveLink: "https://juanp-vt.github.io/cv-app/",
      githubLink: "https://github.com/JuanP-VT/cv-app",
      featured: false,
      level: "Learning",
    },
    {
      title: "Weather Forecast App | Global Weather Lookup",
      description: "Built a weather application that fetches real-time data and a five-day forecast for any location worldwide. Focused on API integration, reading third-party documentation, and improving code quality with linters and cleaner styling.",
      image: "/img/projects/learning/weather.webp",
      tags: ["JavaScript", "HTML", "CSS"],
      liveLink: "https://juanp-vt.github.io/Weather-App/",
      githubLink: "https://github.com/JuanP-VT/Weather-App",
      featured: false,
      level: "Learning",
    },
  ];

  const getProjects = () => data;
  return { getProjects };
}