import type { Project } from "@/types/project.type";
import { useTranslations } from "next-intl";

export function useProjects() {
	const t = useTranslations("projects");
	const data: Project[] = [
		{
			title: t("os2-title"),
			description: t("os2-description"),
			image: "/img/projects/onsite2/main.webp",
			tags: ["TypeScript", "React", "Next.js", "Tailwind CSS"],
			featured: true,
			level: "Professional",
			caseStudyLink: "/cases/onsite2",
			liveLink: "https://onsite-pkt1-v2-test.vercel.app/",
			disclaimer: t("os2-disclaimer"),
		},
		{
			title: t("management-title"),
			description: t("management-description"),
			image: "/img/projects/management/main.webp",
			tags: ["JavaScript", "React", "Tailwind CSS"],
			liveLink: "https://mgmtview.pktuno.mx/",
			featured: false,
			level: "Professional",
			caseStudyLink: "/cases/management",
		},
		{
			title: t("onsite1-title"),
			description: t("onsite1-description"),
			image: "/img/projects/onsite/main.webp",
			tags: ["JavaScript", "jQuery", "HTML", "CSS"],
			liveLink: "https://onsite.pktuno.mx",
			featured: false,
			level: "Professional",
		},
		{
			title: t("internal-tooling-title"),
			description: t("internal-tooling-description"),
			image: "/img/projects/tooling/main.webp",
			tags: ["TypeScript", "Node.js", "SQL", "Express.js", "NestJS"],
			githubLink: "https://github.com/JuanP-VT/internal-tooling-api",
			featured: false,
			level: "Professional",
		},
		{
			title: t("regina-title"),
			description: t("regina-description"),
			image: "/img/projects/regina/main.webp",
			tags: [
				"TypeScript",
				"React",
				"Next.js",
				"Tailwind CSS",
				"MongoDB",
				"AWS",
			],
			liveLink: "https://regis-beta.vercel.app/",
			githubLink: "https://github.com/JuanP-VT/regis",
			caseStudyLink: "/cases/regina",
			featured: false,
			level: "Freelance",
			disclaimer: t("regina-disclaimer"),
		},
		{
			title: t("temazcal-title"),
			description: t("temazcal-description"),
			image: "/img/projects/okahey/main.webp",
			tags: ["TypeScript", "React", "Next.js", "Tailwind CSS"],
			liveLink: "https://temazcal.vercel.app/",
			githubLink: "https://github.com/JuanP-VT/okahey",
			featured: false,
			level: "Freelance",
			disclaimer: t("temazcal-disclaimer"),
		},

		{
			title: t("pchub-title"),
			description: t("pchub-description"),
			image: "/img/projects/learning/pc-hub.webp",
			tags: ["TypeScript", "React", "Next.js", "Tailwind CSS", "MongoDB"],
			liveLink: "https://store-juanp-vt.vercel.app",
			githubLink: "https://github.com/JuanP-VT/pc-ecommerce",
			featured: true,
			level: "Learning",
			caseStudyLink: "/cases/pc-hub",
		},
		{
			title: t("inventory-title"),
			description: t("inventory-description"),
			image: "/img/projects/learning/inventory.webp",
			tags: ["JavaScript", "React", "Express.js", "MongoDB"],
			liveLink: "https://juanp-vt.github.io/store-inventory/",
			githubLink: "https://github.com/JuanP-VT/store-inventory",
			featured: false,
			level: "Learning",
		},
		{
			title: t("fortnite-title"),
			description: t("fortnite-description"),
			image: "/img/projects/learning/shopping-card.webp",
			tags: ["TypeScript", "React", "CSS"],
			liveLink: "https://juanp-vt.github.io/shop-app/",
			githubLink: "https://github.com/JuanP-VT/shop-app",
			featured: false,
			level: "Learning",
			disclaimer: t("fortnite-disclaimer"),
		},
		{
			title: t("curriculum-title"),
			description: t("curriculum-description"),
			image: "/img/projects/learning/cv.webp",
			tags: ["TypeScript", "React", "CSS"],
			liveLink: "https://juanp-vt.github.io/cv-app/",
			githubLink: "https://github.com/JuanP-VT/cv-app",
			featured: false,
			level: "Learning",
		},
		{
			title: t("weather-title"),
			description: t("weather-description"),
			image: "/img/projects/learning/weather.webp",
			tags: ["JavaScript", "HTML", "CSS"],
			liveLink: "https://juanp-vt.github.io/Weather-App/",
			githubLink: "https://github.com/JuanP-VT/Weather-App",
			featured: false,
			level: "Learning",
		},
		{
			title: t("library-title"),
			description: t("library-description"),
			image: "/img/projects/learning/library.webp",
			tags: ["JavaScript", "HTML", "CSS"],
			liveLink: "https://juanp-vt.github.io/Library/",
			githubLink: "https://github.com/JuanP-VT/Library",
			featured: false,
			level: "Learning",
		},
		{
			title: t("todo-title"),
			description: t("todo-description"),
			image: "/img/projects/learning/todo.webp",
			tags: ["JavaScript", "HTML", "CSS"],
			liveLink: "https://juanp-vt.github.io/To-Do-List/",
			githubLink: "https://github.com/JuanP-VT/To-Do-List",
			featured: false,
			level: "Learning",
		},
		{
			title: t("restaurant-title"),
			description: t("restaurant-description"),
			image: "/img/projects/learning/restaurant.webp",
			tags: ["JavaScript", "HTML", "CSS"],
			liveLink: "https://juanp-vt.github.io/Restaurant-Page/",
			githubLink: "https://github.com/JuanP-VT/Restaurant-Page",
			featured: false,
			level: "Learning",
		},
		{
			title: t("etch-title"),
			description: t("etch-description"),
			image: "/img/projects/learning/etch.webp",
			tags: ["JavaScript", "HTML", "CSS"],
			liveLink: "https://juanp-vt.github.io/ETCH-A-SKETCH/",
			githubLink: "https://github.com/JuanP-VT/ETCH-A-SKETCH",
			featured: false,
			level: "Learning",
		},
		{
			title: t("tictactoe-title"),
			description: t("tictactoe-description"),
			image: "/img/projects/learning/tic.webp",
			tags: ["JavaScript", "HTML", "CSS"],
			liveLink: "https://juanp-vt.github.io/Tic-tac-toe/",
			githubLink: "https://github.com/JuanP-VT/Tic-tac-toe",
			featured: false,
			level: "Learning",
		},
		{
			title: t("rps-title"),
			description: t("rps-description"),
			image: "/img/projects/learning/rps.webp",
			tags: ["JavaScript", "HTML", "CSS"],
			liveLink: "https://juanp-vt.github.io/Rock-Paper-Scissors/",
			githubLink: "https://github.com/JuanP-VT/Rock-Paper-Scissors",
			featured: false,
			level: "Learning",
		},
		{
			title: t("signup-title"),
			description: t("signup-description"),
			image: "/img/projects/learning/sign.webp",
			tags: ["HTML", "CSS"],
			liveLink: "https://juanp-vt.github.io/Sign-up-page/",
			githubLink: "https://github.com/JuanP-VT/Sign-up-page",
			featured: false,
			level: "Learning",
		},
		{
			title: t("landing-title"),
			description: t("landing-description"),
			image: "/img/projects/learning/landing.webp",
			tags: ["HTML", "CSS"],
			liveLink: "https://juanp-vt.github.io/Landing-page/",
			githubLink: "https://github.com/JuanP-VT/Landing-page",
			featured: false,
			level: "Learning",
		},
	];

	const getProjects = () => data;
	return { getProjects };
}
