import type { Project } from "@/types/project.type";
import { useTranslations } from "next-intl";

export function useProjects() {
	const t = useTranslations("projects");
	const data: Project[] = [
		{
			title: t("os2-title"),
			description: t("os2-description"),
			image: "/img/projects/onsite2/main.webp",
			tags: ["TypeScript", "React", "Next.js", "Tailwind CSS"],
			liveLink: "#",
			githubLink: "#",
			featured: true,
			level: "Professional",
			caseStudyLink: "/cases/onsite2",
		},
		{
			title: t("management-title"),
			description: t("management-description"),
			image: "/img/projects/management/main.webp",
			tags: ["JavaScript", "React", "Tailwind CSS"],
			liveLink: "#",
			githubLink: "#",
			featured: false,
			level: "Professional",
			caseStudyLink: "/cases/management",
		},
		{
			title: t("onsite1-title"),
			description: t("onsite1-description"),
			image: "/img/projects/onsite/main.webp",
			tags: ["JavaScript", "jQuery", "HTML", "CSS"],
			liveLink: "#",
			githubLink: "#",
			featured: false,
			level: "Professional",
		},
		{
			title: t("internal-tooling-title"),
			description: t("internal-tooling-description"),
			image: "/img/projects/tooling/main.webp",
			tags: ["TypeScript", "Node.js", "SQL", "Express.js", "NestJS"],
			liveLink: "#",
			githubLink: "#",
			featured: false,
			level: "Professional",
		},
		{
			title: t("temazcal-title"),
			description: t("temazcal-description"),
			image: "/img/projects/okahey/main.webp",
			tags: ["TypeScript", "React", "Next.js", "Tailwind CSS"],
			liveLink: "#",
			githubLink: "#",
			featured: false,
			level: "Freelance",
		},
		{
			title: t("regina-title"),
			description: t("regina-description"),
			image: "/img/projects/regina/main.webp",
			tags: [
				"TypeScript",
				"React",
				"Next.js",
				"Tailwind CSS",
				"MongoDB",
				"AWS",
			],
			liveLink: "#",
			githubLink: "#",
			featured: false,
			level: "Freelance",
		},
		{
			title: t("pchub-title"),
			description: t("pchub-description"),
			image: "/img/projects/learning/pc-hub.webp",
			tags: ["TypeScript", "React", "Next.js", "Tailwind CSS", "MongoDB"],
			liveLink: "#",
			githubLink: "#",
			featured: true,
			level: "Learning",
		},
		{
			title: t("inventory-title"),
			description: t("inventory-description"),
			image: "/img/projects/learning/inventory.webp",
			tags: ["JavaScript", "React", "Express.js", "MongoDB"],
			liveLink: "#",
			githubLink: "#",
			featured: false,
			level: "Learning",
		},
		{
			title: t("fortnite-title"),
			description: t("fortnite-description"),
			image: "/img/projects/learning/shopping-card.webp",
			tags: ["TypeScript", "React", "CSS"],
			liveLink: "#",
			githubLink: "#",
			featured: false,
			level: "Learning",
		},
		{
			title: t("curriculum-title"),
			description: t("curriculum-description"),
			image: "/img/projects/learning/cv.webp",
			tags: ["TypeScript", "React", "CSS"],
			liveLink: "#",
			githubLink: "#",
			featured: false,
			level: "Learning",
		},
		{
			title: t("weather-title"),
			description: t("weather-description"),
			image: "/img/projects/learning/weather.webp",
			tags: ["JavaScript", "HTML", "CSS"],
			liveLink: "#",
			githubLink: "#",
			featured: false,
			level: "Learning",
		},
		{
			title: t("library-title"),
			description: t("library-description"),
			image: "/img/projects/learning/library.webp",
			tags: ["JavaScript", "HTML", "CSS"],
			liveLink: "#",
			githubLink: "#",
			featured: false,
			level: "Learning",
		},
		{
			title: t("todo-title"),
			description: t("todo-description"),
			image: "/img/projects/learning/todo.webp",
			tags: ["JavaScript", "HTML", "CSS"],
			liveLink: "#",
			githubLink: "#",
			featured: false,
			level: "Learning",
		},
		{
			title: t("restaurant-title"),
			description: t("restaurant-description"),
			image: "/img/projects/learning/restaurant.webp",
			tags: ["JavaScript", "HTML", "CSS"],
			liveLink: "#",
			githubLink: "#",
			featured: false,
			level: "Learning",
		},
		{
			title: t("etch-title"),
			description: t("etch-description"),
			image: "/img/projects/learning/etch.webp",
			tags: ["JavaScript", "HTML", "CSS"],
			liveLink: "#",
			githubLink: "#",
			featured: false,
			level: "Learning",
		},
		{
			title: t("tictactoe-title"),
			description: t("tictactoe-description"),
			image: "/img/projects/learning/tic.webp",
			tags: ["JavaScript", "HTML", "CSS"],
			liveLink: "#",
			githubLink: "#",
			featured: false,
			level: "Learning",
		},
		{
			title: t("rps-title"),
			description: t("rps-description"),
			image: "/img/projects/learning/rps.webp",
			tags: ["JavaScript", "HTML", "CSS"],
			liveLink: "#",
			githubLink: "#",
			featured: false,
			level: "Learning",
		},
		{
			title: t("admin-title"),
			description: t("admin-description"),
			image: "/img/projects/learning/admin.webp",
			tags: ["HTML", "CSS"],
			liveLink: "#",
			githubLink: "#",
			featured: false,
			level: "Learning",
		},
		{
			title: t("signup-title"),
			description: t("signup-description"),
			image: "/img/projects/learning/sign.webp",
			tags: ["HTML", "CSS"],
			liveLink: "#",
			githubLink: "#",
			featured: false,
			level: "Learning",
		},
		{
			title: t("landing-title"),
			description: t("landing-description"),
			image: "/img/projects/learning/landing.webp",
			tags: ["HTML", "CSS"],
			liveLink: "#",
			githubLink: "#",
			featured: false,
			level: "Learning",
		},
	];

	const getProjects = () => data;
	return { getProjects };
}
