import type { Metadata } from 'next';
import '../globals.css';
import { ThemeProvider } from 'next-themes';
import { NextIntlClientProvider, hasLocale } from 'next-intl';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
import localFont from 'next/font/local';

const sfMono = localFont({
  src: '../../../public/fonts/SFMono-Regular.otf',
});
export const metadata: Metadata = {
  title: 'Juan Pablo | Developer',
  description: 'Generated by create next app',
};

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={`${sfMono.className} bg-[#f5f9f9] antialiased dark:bg-[#1a202c]`}>
        <NextIntlClientProvider>
          <ThemeProvider attribute="class" defaultTheme="dark">
            {children}
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
